# APP
spring.application.name=justbinary

# DATABASE (MongoDB Atlas)
spring.data.mongodb.uri=mongodb+srv://emmanuelkipngeno799_db_user:Chepkoech1978@cluster0.nkscyto.mongodb.net/justbinary

# JWT
jwt.secret=justbinarySecretKey123456789012345
jwt.expiration=86400000

# SERVER
server.port=8080

# MPESA PRODUCTION
mpesa.base-url=https://api.safaricom.co.ke
mpesa.consumer-key=3OMVcMAYNXGXKo4MS8r7TnylAnzFmERTdTvvcG0Sf4PjiELl
mpesa.consumer-secret=GrpZKfGGeGW1kA7D23xH1vkhNtvMMvRAFGE1wbog8NzH7nJsuv87dOAHGWDGe1W3
mpesa.shortcode=8997462
mpesa.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
mpesa.callback-url=https://bestbinary-production-c9bb.up.railway.app/api/mpesa/callback
mpesa.transaction-type=CustomerBuyGoodsOnline

# DARAJA STK PUSH
daraja.consumer-key=JhcqqkAlYNiuON3q7UZNRAkMLaKhQn2cDKiWeWP1tEQz8JGO
daraja.consumer-secret=2fGllj8R74E0U9d4BY8Ao3Jp3cNMuLuNjEfr0wXYpJlAAODufguSsFxjFGZouR4A
daraja.shortcode=8997462
daraja.till-number=8997462
daraja.transaction-type=CustomerBuyGoodsOnline
daraja.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
daraja.base-url=https://api.safaricom.co.ke
daraja.callback-url=https://bestbinary-production-c9bb.up.railway.app/api/payments/mpesa-callback
daraja.usd-to-kes=129.0

# PESAPAL
pesapal.consumer-key=xPPYUL3Ap360RqeZUX6xaFabY/cX6hHK
pesapal.consumer-secret=S2CzhZNLN3Z7IylIO2t0V5pWV7M=
pesapal.base-url=https://pay.pesapal.com/v3
pesapal.callback-url=https://bestbinary-production-c9bb.up.railway.app/api/pesapal/callback
pesapal.ipn-url=https://bestbinary-production-c9bb.up.railway.app/api/pesapal/ipn

# LOGGING
logging.level.com.justbinary=DEBUG
logging.level.org.springframework.security=DEBUG